services:
  influxql-gui:
    build: .
    container_name: "influxql-gui"
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - INFLUXDB_SERVER_URI=http://influxdb:8086
      - INFLUXDB_SERVER_TOKEN=your-token    

